[build]
builder = "NIXPACKS"

[deploy]
startCommand = "./startup.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = [
  "NODE_ENV=production",
  "JWT_SECRET=some_jwt_secret",
  "COOKIE_SECRET=some_cookie_secret",
  "MEDUSA_ADMIN_BACKEND_URL=${{RAILWAY_PUBLIC_DOMAIN}}",
  "ADMIN_CORS=*"
]
